### PR TITLE
refactor: simplifying traits scan

### LINKED ISSUE #30: Simplify the scanning process by disabling `applyTraits` flag on parser-js
#### Reason/Context
This library assumes that there is no way to disable 'traits applying' on parser but there is a flag to disable it. By disabling the `applyTraits` the scanning of the traits become easier and the codebase becomes simpler.

#### Description
First of all, we have to set `applyTraits` flag to `false` when parsing the AsyncAPI specification file.
After disabling it, the `ComponentsProvider` class becomes much simpler, because we don't have to figure out if the field is coming from traits or it was in the field itself. we can scan them separately.

### PR DESCRIPTION
**Pull request by KhudaDad414**
**Description**

- this PR will make scanning traits simpler and easier by not applying them to the components.

**Related issue(s)**
Resolves #30

### CODE REVIEW

**Comment by magicmatatjahu** [comment]
@KhudaDad414 Shouldn't the new code be tested? Is there a case here that is included and wasn't?

**Comment by magicmatatjahu** [comment]
@KhudaDad414 Thanks for explanation! Ok, I don't want to block you.

**Review by magicmatatjahu — APPROVED** [review]

**Comment by magicmatatjahu** [comment]
@KhudaDad414 One last thing. Do you think there are cases when traits can be merged first and optimized later? I can't imagine, but maybe you have some?

**Comment by derberg** [comment]
Purpose of the optimizer is to optimize the document before it hits tooling like code generator or docs display, so definitely before traits application, its raw version. 

The other problem I see here that we optimize parsed document, which means we optimize it after dereferencing, and this can be a problem

**Comment by KhudaDad414** [comment]
> @KhudaDad414 One last thing. Do you think there are cases when traits can be merged first and optimized later? I can't imagine, but maybe you have some? 

That's a great question and it gave me some ideas about traits optimization in the future.

Plan A:
1) generate a report the traditional way.
2) generate a report with traits being merged.
3) compare t two reports (comparation criteria can be based on output size and simplicity of the output maybe?).
4) select one of them(automatically or maybe we can have a flag?)
5) apply changes on the output.

I will open an issue when I evaluate other options as well.🙂

**Comment by KhudaDad414** [comment]
> Purpose of the optimizer is to optimize the document before it hits tooling like code generator or docs display, so definitely before traits application, its raw version. 
 
@derberg I genuinely don't understand what the purpose of traits is besides components reuse. Is there any other purpose? (Happy to read more about them if there is any resources😀).

> The other problem I see here that we optimize parsed document, which means we optimize it after dereferencing, and this can be a problem


We don't optimize the parsed document, we just use the parsed version for report generation(because it provides many useful methods). The report result will be applied to the original document that is passed.

**Comment by magicmatatjahu** [comment]
> The other problem I see here that we optimize parsed document, which means we optimize it after dereferencing, and this can be a problem

At the moment inside the library it's checked first that the given object is used as a reference - Khuda once asked how to do that and it's enough to use `===` between two JS objects. I myself believe that doing an optimization before dereferencing would probably be the best solution, but `dereference: false` should be supported in parserJS first.

**Comment by derberg** [comment]
> @derberg I genuinely don't understand what the purpose of traits is besides components reuse. Is there any other purpose? (Happy to read more about them if there is any resources😀).

it is exactly for that, for keeping it DRY, so they can be one of the ways to optimize the document for the user with this library

> We don't optimize the parsed document, we just use the parsed document for report generation(because it provides many useful methods). The report result will be applied to the original document that is passed.

eventually, report should be done on not dereferenced document

> The library can differentiate between dereferenced and "declared" components and it only operates on declared ones. So I don't see what the problem is here

why not operating on refed parts? it is ok for now to have limits like this, or limits like (we do not support optimizations if you have external refs) but just long term we should address it too. 

just check out what happens when you refer component that also has refs, and it is refed but also can be used for optimization (hehe, English is not my strong side). Just play with 👇🏼 and see the bad things that happen, my suspicion is that it is caused by operating on dereferenced file when doing a report - did not check-in details. Anyway better create a separate issue about it for future.
```
asyncapi: 2.0.0
info:
  title: Streetlights API
  version: '1.0.0'
channels:
  smartylighting/event/lighting/measured:
    subscribe:
      message:
        $ref: "#components/messages/unusedMessage"
  smartylighting/event/{streetlightId}/lighting/measured:
    parameters:
      #this parameter is duplicated. it can be moved to components and ref-ed from here.
      streetlightId:
        schema:
          type: string
    subscribe:
      operationId: receiveLightMeasurement
      traits:
        - bindings:
            kafka:
              clientId: my-app-id
      message:
        name: unusedMessage
        title: This message is not used in any channel.
  smartylighting/action/{streetlightId}/turn/on:
    parameters:
      streetlightId:
        schema:
          type: string
    publish:
      operationId: turnOn
      traits:
        - bindings:
            kafka:
              clientId: my-app-id
      message:
        name: turnOnOff
        title: Turn on/off
        traits:
          - headers:
              type: object
              properties:
                my-app-header:
                  type: integer
                  minimum: 0
                  maximum: 100
        payload:
          type: object
          properties:
            sentAt:
              $ref: "#/components/schemas/sentAt"
components:
  messages:
    #libarary should be able to find and delete this message, because it is not used anywhere.
    unusedMessage:
      name: unusedMessage
      title: This message is not used in any channel.
      payload:
        $ref: "#/components/schemas/sentAt"
  schemas:
    #this schema is ref-ed in one channel and used full form in another. library should be able to identify and ref the second channel as well.
    sentAt:
      type: string
      format: date-time
```

> but dereference: false should be supported in parserJS first

not as easy as it may sound, I disabled it when working on support for circular refs, saw no other solution at a time

**Comment by KhudaDad414** [comment]
@derberg I tested the file and only found one issue with this file. it will remove `components/messages/unusedMessage` even though it is used above? is that it?

**Comment by derberg** [comment]
yes, and when you remove a reference to payload from `unusedMessage`, basically remove payload, it works fine. Thus I assume it is related to wrong report caused by operating on parser parsed AsyncAPI doc. Of course it may be something totally different :D

**Comment by KhudaDad414** [comment]
@derberg this happens because of a typo in your document.
It should be `$ref: "#/components/messages/unusedMessage"` not `$ref: "#components/messages/unusedMessage"`.
Take a look at [this issue](https://github.com/asyncapi/parser-js/issues/360).

**Comment by derberg** [comment]
ups, sorry 🤦🏼

**Pull request merged**
