### PR TITLE
chore: add @aeworxet and remove @derberg and @magicmatatjahu as CODEOWNERS

### PR DESCRIPTION
**Pull request by KhudaDad414**
**Description**

- I propose we add @aeworxet as a code owner. I justify this for the following contribution:
    - #235
    - #216 
    - #215
    - #213
    - #212
- based on [the request](https://github.com/asyncapi/optimizer/pull/252#issuecomment-2061170696) from @derberg I am removing him.
- I assume @magicmatatjahu also wants to remove himself based on @derberg's comment.

### CODE REVIEW

**Review by derberg — APPROVED** [review]
excelent decision!

please do not remember after merging to invite @aeworxet to repo and remove me and @magicmatatjahu from permissions settings

**Comment by magicmatatjahu** [comment]
@KhudaDad414 Thanks! :)

**Review by magicmatatjahu — APPROVED** [review]

**Comment by aeworxet** [comment]
I accept and am happy to join.

**Pull request merged**
